---
- name: Install web server
  hosts: webservers
  remote_user: ubuntu
  become: yes
  roles: 
  - roles/iti-webserver-role

- name: Install web server
  hosts: jenkinsserver
  remote_user: ec2-user
  become: yes
  roles: 
  - roles/jenkins-role

- name: Install web server
  hosts: dbservers
  remote_user: ec2-user
  become: yes
  vars_files:
    - roles/mariadb/vars/secret.yml
  
  roles: 
  - roles/mariadb
