---
# tasks file for jenkins-role
- name: Download repo
  ansible.builtin.get_url:
    url:  https://pkg.jenkins.io/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io.key

- name: Install the latest version of java-11-openjdk
  ansible.builtin.yum:
    name: java-11-openjdk
    state: present

- name: Install the latest version of jenkins
  ansible.builtin.yum:
    name: jenkins
    state: latest

- name: start jenkins
  ansible.builtin.systemd:
    name: jenkins
    enabled: yes
    state: started